import { AssetType } from "@bridged.xyz/client-sdk/lib/assets"
import { keyNameFormatValidation } from "@bridged.xyz/client-sdk/lib/g11n/validators/key-name.validate"
import * as dynamoose from "dynamoose"
import { nanoid } from "nanoid"
/**
 * the key manifest for globallized assets.
 * unique with ( projectId && type && keyName )
 */
export interface KeyRecord {
    /**
     * the id of this key generated by server
     */
    id: string

    /**
     * the project of this key being assosiated
     */
    projectId: string

    /**
     * name of the key, commonly said as just "key" on the client side.
     */
    keyName: string

    /**
     * type of asset to be linked with this key.
     */
    type: AssetType

    /**
     * configuration of availability of this key being embedded by other key.
     * defaults to false
     * 
     * if embeddable set to true, this key will be visible for search results of key.
     * if embeddable 'changed' to false, all the referening assets will be replaced with last known value & localse of this key's asset.
     */
    embeddable: boolean
}

/**
 * maps scene's layer and asset's key together
 */
export interface LayerKeyMapRecord {
    /**
     * the id of the key
     */
    keyId: string

    /**
     * the id of the layer
     */
    layerId: string
}

const KeySchema = new dynamoose.Schema({
    id: {
        required: true,
        type: String,
        forceDefault: true,
        hashKey: true,
        default: () => nanoid()
    },
    projectId: {
        type: String,
        required: true
    },
    keyName: {
        type: String,
        required: true,
        validate: (v: string) => keyNameFormatValidation(v)
    },
    type: {
        type: String,
        enum: ["URI", "TEXT", "IMAGE", "ICON", "ILLUST", "COLOR", "FILE", "UNKNOWN"]
    },
    embeddable: {
        type: Boolean,
        default: false,
    }
}, {
    saveUnknown: false
})

const KEY_TABLE_NAME = process.env.DYNAMO_KEY_TABLE
export const KeyModel = dynamoose.model(KEY_TABLE_NAME, KeySchema, {
    create: false
})