import { AssetType } from "@bridged.xyz/client-sdk/lib"


/**
 //  * the table definition of asset. the asset can be temporary, and it does not contains any information of which holds this asset.
 */
export interface AssetTable {
    id: string
    name: string
    type: AssetType
    value: string
    tags?: string[]
}

/**
 * record of project's managed variant asset.
 * unique with (project-id & key & type)
 */
export interface VariantAssetTable {
    /**
     * id generated by the server
     */
    id: string

    /**
     * the id of the project. (this is not a file id!)
     * i.e. figma project is not a bridged project. multiple projects on the design tools can be a single project on bridged system.
     */
    projectId: string

    /**
     * *REQUIRED*
     * key of this variant asset. 
     */
    key: string

    /**
     * *REQUIRED*
     * explicit name set by editor
     */
    name: string

    /**
     * description of this localized, variantized asset set by editor
     */
    description?: string

    /**
     * *REQUIRED*
     * type of asset alias
     */
    type: AssetType

    /**
     * *REQUIRED*
     *  variant : asset id
     * e.g. "en_US": "G2ggs93", where 'G2ggs93' is an id of asset
     *  */
    assets: Map<string, string>


    tags?: string[]
}
